---
- hosts: localhost
  connection: local
  sudo: yes

  vars_files:
    - vars.yml

  tasks:
    - include: tasks/base.yml tags=base
    - include: tasks/apps.yml tags=apps
    - include: tasks/zsh.yml tags=zsh
    - include: tasks/chruby.yml tags=ruby
    - include: tasks/ruby-install.yml tags=ruby
    #- include: tasks/desktop.yml tags=desktop

- hosts: localhost
  connection: local
  sudo: no

  vars_files:
    - vars.yml

  tasks:
    - include: tasks/dotfiles.yml tags=dotfiles
