# Install and configure system apps
#
#
# Copyright (C) 2013 Calogero Lo Leggio <kalos@nerdrug.org>
#
# This part of software is released under the terms of the GPLv3 license.
#
---
- name: install system apps
  apt: pkg={{ item }} state=installed
  with_items:
    - vim
    - less
    - psmisc
    - htop
    - tree
    - ack-grep

- name: Install selecta
  sudo: false
  get_url: url=https://raw.githubusercontent.com/garybernhardt/selecta/master/selecta dest=/home/{{user}}/bin/selecta mode=u+x
