# Base settings for debian/APT, configure sudo and NTP
#
#
# Copyright (C) 2013 Calogero Lo Leggio <kalos@nerdrug.org>
#
# This part of software is released under the terms of the GPLv3 license.
#

- name: Create home directories
  sudo: false
  file: path=/home/{{user}}/{{item}} state=directory mode=0755
  with_items:
    - dev
    - bin

- name: install ectkeeper
  apt: name=etckeeper state=installed

# { NTP
- name: install ntpdate
  apt: name=ntpdate state=installed
  register: ntpdate

- name: exec ntpdate
  command: ntpdate-debian
  when: ntpdate.changed

- name: install NTP deamon
  apt: name=ntp state=installed

- name: NTP should be running
  service: name=ntp state=running enabled=yes
# }
