---
- name: install Chrome stable
  sudo: true
  apt: name=google-chrome-stable state=installed


- name: Install latest chromium package with codecs
  apt: pkg="{{ item }}" state=present force=yes
  with_items:
    - chromium-browser
    - chromium-browser-l10n
    - chromium-codecs-ffmpeg-extra
