# Install chruby and gem_home
#
#
---
- name: Check chruby installed
  stat: path=/usr/local/share/chruby
  register: stat_chruby

- name: Create working directory
  file:
    path: /usr/src
    state: directory

- name: Download chruby
  get_url:
    url: https://github.com/postmodern/chruby/archive/v{{ chruby_version }}.tar.gz
    dest: /usr/src/chruby-{{ chruby_version }}.tar.gz
  when: stat_chruby.stat.isdir is not defined
  register: chruby_downloaded

- name: Extract chruby
  shell: tar -C /usr/src -xzvf /usr/src/chruby-{{ chruby_version }}.tar.gz
  when: chruby_downloaded.changed
  register: chruby_extracted

- name: Install chruby
  shell: cd /usr/src/chruby-{{ chruby_version }}/ && make install
  when: chruby_extracted | changed
  register: chruby_installed

- name: Clean up chruby sources
  shell: rm -rf /usr/src/chruby-*
  when: chruby_downloaded.changed

- name: Check gem_home  installed
  stat: path=/usr/local/share/gem_home
  register: stat_gem_home

- name: Download gem_home
  get_url:
    url: https://github.com/postmodern/gem_home/archive/v{{ gem_home_version }}.tar.gz
    dest: /usr/src/gem_home-{{ gem_home_version }}.tar.gz
  when: stat_gem_home.stat.isdir is not defined
  register: gem_home_downloaded

- name: Extract gem_home
  shell: tar -C /usr/src -xzvf /usr/src/gem_home-{{ gem_home_version }}.tar.gz
  when: gem_home_downloaded.changed
  register: gem_home_extracted

- name: Install gem_home
  shell: cd /usr/src/gem_home-{{ gem_home_version }}/ && make install
  when: gem_home_extracted | changed
  register: gem_home_installed

# - name: Clean up gem_home sources
#   shell: rm -rf /usr/src/gem_home-*
#   when: gem_home_downloaded.changed
