# Install chruby
#
#
---
- name: Check chruby installed
  stat: path=/usr/local/share/chruby
  register: stat_chruby

- name: Create working directory
  file:
    path: /usr/src
    state: directory

- name: Download chruby
  get_url:
    url: https://github.com/postmodern/chruby/archive/v{{ chruby_version }}.tar.gz
    dest: /usr/src/chruby-{{ chruby_version }}.tar.gz
  when: stat_chruby.stat.isdir is not defined
  register: chruby_downloaded

- name: Extract chruby
  shell: tar -C /usr/src -xzvf /usr/src/chruby-{{ chruby_version }}.tar.gz
  when: chruby_downloaded.changed
  register: chruby_extracted

- name: Install chruby
  shell: cd /usr/src/chruby-{{ chruby_version }}/ && make install
  when: chruby_extracted | changed
  register: chruby_installed

- name: Clean up chruby sources
  shell: rm -rf /usr/src/chruby-*
  when: chruby_downloaded.changed
