---
# Install Lein
- name: Install Lein (Clojure project automation)
  get_url:
    url: https://raw.githubusercontent.com/technomancy/leiningen/stable/bin/lein
    dest: /home/{{user}}/bin/lein
    mode: 0755

- name: Install lein user profiles.clj
  sudo: false
  template: src=templates/lein-profiles.clj dest=/home/{{user}}/.lein/lein-profiles.clj

# http://ppa.launchpad.net/gnome-terminator/ppa/ubuntu bionic Release' does not have a Release file.
# - name: Add PPA for Planck
#   sudo: true
#   apt_repository: repo='ppa:mfikes/planck' state=present

- name: Install Planck (ClojureScript REPL)
  apt: name=planck state=installed

- name: Chicken (Scheme to C)
  apt: name=chicken-bin state=installed

