---
- name: Install Redis
  apt: name=redis-server state=installed

- name: Install ElasticSearch
  apt: name=elasticsearch state=installed

- name: Install MySQL
  apt: name=mysql-server state=installed

- name: Install MySQL Development headers
  apt: name=libmysqlclient-dev state=installed

- name: MySQL should be running
  service: name=mysql state=running enabled=yes

- name: Symlink MySQL socket
  sudo: false
  file: src=/run/mysqld/mysqld.sock dest=/tmp/mysql.sock state=link

- name: Install SQLite
  apt: name=sqlite3 state=installed

- name: Install SQLite3 development headers
  apt: name=libsqlite3-dev state=installed
