---
- name: Install Redis
  apt: name=redis-server state=installed

- name: Install ElasticSearch
  apt: name=elasticsearch state=installed

  # https://discuss.elastic.co/t/cant-start-elasticsearch-with-ubuntu-16-04/48730/9
- name: Fix ElasticSearch config
  sudo: true
  command: "sed -i 's/#START_DAEMON/START_DAEMON/' /etc/default/elasticsearch"

- name: Install MySQL
  apt: name=mysql-server state=installed

- name: Install MySQL Development headers
  apt: name=libmysqlclient-dev state=installed

- name: MySQL should be running
  service: name=mysql state=running enabled=yes

- name: Copy MySQL client configuration
  sudo: false
  copy: src=templates/my.cnf dest=/home/{{user}}/.my.cnf

# http://mycli.net/
- name: Install MyCLI
  apt: name=mycli state=installed

- name: Copy myCLI configuration
  sudo: false
  copy: src=templates/myclirc dest=/home/{{user}}/.myclirc

- name: Install MySQL Workbench
  apt:  name=mysql-workbench state=installed

- name: Symlink MySQL socket
  sudo: false
  file: src=/var/run/mysqld/mysqld.sock dest=/tmp/mysql.sock state=link

- name: Install SQLite
  apt: name=sqlite3 state=installed

- name: Install SQLite3 development headers
  apt: name=libsqlite3-dev state=installed

- name: Install RabbitMQ
  sudo: true
  apt: name=rabbitmq-server state=installed

- name: Install Postgres Database
  sudo: true
  apt: pkg=$item state=installed
  with_items:
    - postgresql
    - postgresql-contrib
    - libpq-dev
