
- name: Add Docker PPA key
  sudo: true
  apt_key: url=https://download.docker.com/linux/ubuntu/gpg state=present

- name: Add Docker PPA
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ubuntu_release_name }} stable"
  sudo: true

- name: Install Docker
  apt: name={{item}}
  with_items:
    - apt-transport-https
    - ca-certificates
    - curl
    - software-properties-common
    - docker-ce

- name: Install Docker Compose
  get_url:
    url: https://github.com/docker/compose/releases/download/1.22.0/docker-compose-Linux-x86_64
    dest: "/home/{{user}}/bin/docker-compose"
    mode: 0755
