---
- name: Install Git
  apt: name={{item}} state=installed
  with_items:
    - git
    - gitk

- name: Copy .gitconfig
  sudo: false
  template: src=templates/gitconfig dest=~/.gitconfig force=yes

