---
- name: Install Git
  apt: name={{item}} state=installed
  with_items:
    - git
    - gitk

- name: Copy .gitconfig
  become: false
  template: src=templates/gitconfig dest=/home/{{user}}/.gitconfig force=yes

- name: Lepton (gist manager)
  apt: name=lepton state=present
