---
- name: install compizconfig manager
  apt: name=compizconfig-settings-manager state=installed

# when an luncher icon is clicked it opens the app, click again to minimise
- name: Launcher minimise on click
  sudo: false
  command: "gsettings set org.compiz.unityshell:/org/compiz/profiles/unity/plugins/unityshell/ launcher-minimize-window true"


# https://faq.i3wm.org/question/1/how-can-i-get-rid-of-the-nautilus-desktop-window.1.html
- name: Prevent desktop showing when opening Nautilus
  sudo: false
  command: " gsettings set org.gnome.desktop.background show-desktop-icons false"

