---
- name: install Gnome standard themes
  apt: name=gnome-themes-standard state=installed

- name: Install Conky
  apt: name=conky state=installed

- name: Copy .conkyrc
  sudo: false
  template: src=templates/conkyrc dest=/home/{{user}}/.conkyrc
