---
- name: Install Imagemagick (+ headers)
  apt: pkg={{ item }} state=installed
  with_items:
    - imagemagick
    - libmagickwand-dev

- name: Install GraphViz
  apt: pkg=graphviz state=installed
