---
- name: install i3 Window Manager
  apt: name=i3 state=installed

  # xdotool is used in i3 config to map Super+c to Ctrl+c etc.
- name: install xdotool
  apt: name=xdotool state=installed

# alternative i3 application launcher
- name: Install rofi (app launcher)
  apt: name=rofi state=installed

- name: Create i3 config directories
  sudo: false
  file: path=/home/{{user}}/.config/{{item}} state=directory mode=0755
  with_items:
    - i3
    - i3status

- name: Copy i3 conf
  sudo: false
  template: src=templates/i3_config dest=/home/{{user}}/.config/i3/config

- name: Copy i3status conf
  sudo: false
  template: src=templates/i3status_config dest=/home/{{user}}/.config/i3status/config

# nautilus, by default, opens without the --no-desktop option which causes the
# desktop to be shown over the top of the i3 UI.
#
# This fix adds a .desktop file which will be picked up by the i3 application
# launcher instead of the default.
#
- name: Fix Nautilus in i3
  sudo: false
  template: src=templates/nautilus.desktop dest=/home/{{user}}/.local/share/applications

# Compton prevents screen tearing which happens when the screen updates a lot,
# e.g. scrolling or watching videos
#
# https://github.com/chjj/compton
- name: Install Compton
  sudo: true
  apt: name=compton state=installed

- name: Install Feh (wallpaper)
  sudo: true
  apt: name=feh state=installed

- name: Copy wallpapers
  sudo: true
  copy: src=templates/wallpapers/desktop.jpeg dest=/usr/share/backgrounds

# i3 over Gnome
- name: Install Gnome
  sudo: true
  apt: name={{item}} state=installed
  with_items:
    # - gnome-panel
    - gnome-session
    - gnome-settings-daemon

- name: Gnome config
  sudo: true
  template: src=templates/gnome-i3.desktop dest=/usr/share/xsessions

- name: Gnome config
  sudo: true
  template: src=templates/gnome-i3.session dest=/usr/share/gnome-session/sessions

# the Gnome desktop will overlay i3 windows
- name: Turn off Gnome desktop
  sudo: true
  command: gsettings set org.gnome.desktop.background show-desktop-icons false
