---
# Install Javascript tools

- name: Install Node
  apt: name=nodejs state=latest
  sudo: true

- name: Install npm
  apt: name=npm state=latest
  sudo: true

- name: Create npm global directory
  sudo: false
  file: path=~/.npm-global state=directory

- name: Change npm default directory
  sudo: false
  shell: npm config set prefix '~/.npm-global'

- name: Symlink nodejs to node
  sudo: true
  file: src=/usr/bin/nodejs dest=/usr/bin/node state=link

- name: Install Coffeescript
  apt: name=coffeescript state=installed
  sudo: true
