---
- name: Install Keybase
  apt: deb=https://prerelease.keybase.io/keybase_amd64.deb state=installed
  register: keybase_installed

- name: Restart Keybase
  become: false
  command: run_keybase
  when: keybase_installed.changed
