---
- name: Install XClip (copy/paste for the terminal)
  apt: name=xclip state=present

- name: Install ctags
  apt: name=exuberant-ctags state=present

- name: Check NeoVIM installed
  stat: path=/usr/bin/nvim
  register: stat_nvim

- name: Add PPA for NeoVIM
  sudo: true
  apt_repository: repo='ppa:neovim-ppa/unstable' state=present
  when: stat_nvim.stat.exists == False

- name: Install NeoVIM
  sudo: true
  apt: name=neovim state=latest
  # when: stat_nvim.stat.exists == False

- name: Check NeoVIM config installed
  stat: path=/home/{{user}}/.config/nvim
  register: stat_nvim_config

- name: Add NeoVIM configuration
  become: false
  git: repo=git@github.com:krisleech/neovim-config.git
       dest=/home/{{user}}/.config/nvim
       accept_hostkey=yes
  when: stat_nvim_config.stat.exists == False

- name: Install Python client for NeoVim
  pip: name=neovim

# FIXME: hangs because can't find color scheme
# https://github.com/junegunn/vim-plug/issues/730
# - name: Install NeoVIM plugins
#   become: false
#   shell: vim +'PlugInstall --sync' +qall &> /dev/null < /dev/tty
#   when: stat_nvim.stat.exists == False
