---
- name: Add Numix repository
  apt_repository: repo=ppa:numix/ppa
  sudo: true

- name: Install Numix
  apt: name={{item}} state=latest
  sudo: true
  with_items:
    - unity-tweak-tool
    - numix-gtk-theme
    - numix-icon-theme-circle
      #- numix-wallpaper-fs
      #- numix-wallpaper-aurora
