
# - name: install Ruby dependencies
#   apt: pkg={{ item }} state=installed
#   with_items:
#     - zlib1g-dev
#     - libssl-dev
#     - libreadline-dev
#     - libyaml-dev
#     - libsqlite3-dev
#     - sqlite3
#     - libxml2-dev # nokogiri
#     - libxslt-dev # nokogiri
#     - libxslt1-dev # nokogiri
#     - libcurl4-openssl-dev
#     - libffi-dev
#     - libgumbo-dev # nokogumbo


- name: Install system Ruby
  apt: name=ruby state=installed
