
# - name: install Ruby dependencies
#   apt: pkg={{ item }} state=present
#   with_items:
#     - zlib1g-dev
#     - libssl-dev
#     - libreadline-dev
#     - libyaml-dev
#     - libsqlite3-dev
#     - sqlite3
#     - libxml2-dev # nokogiri
#     - libxslt-dev # nokogiri
#     - libxslt1-dev # nokogiri
#     - libcurl4-openssl-dev
#     - libffi-dev
#     - libgumbo-dev # nokogumbo

- name: Install system Ruby
  apt: name=ruby state=present

- name: Persist IRb history (.irbrc)
  become: false
  template: src=templates/irbrc dest=/home/{{user}}/.irbrc

- name: Persist Pry history (.pryrc)
  become: false
  template: src=templates/pryrc dest=/home/{{user}}/.pryrc

