# allows sharing of files on the LAN (folder can be shared within nautilus)
#

- name: 'Install Samba'
  apt: name=samba state=present

- name: Create share directory
  become: false
  file: path=/home/{{user}}/share state=directory mode=0777

- name: Add README to share
  become: false
  template: src=templates/share_README dest=/home/{{user}}/share/README
