---
# Install & Configure Skype

- name: Add terminator repository
  apt_repository: repo="ppa:gnome-terminator"
  sudo: true

- name: Update package manager
  apt: update_cache=yes
  sudo: true

- name: Install Terminator
  apt: name=terminator state=latest
  sudo: true

