---
# Install Virtualbox

- name: Add apt package source
  sudo: true
  apt: deb=http://download.virtualbox.org/virtualbox/5.2.16/virtualbox-5.2_5.2.16-123759~Ubuntu~bionic_amd64.deb

# https://forums.virtualbox.org/viewtopic.php?f=7&t=77363&start=15
