---
- name: Add Yubikey PPA
  apt_repository: repo=ppa:yubico/stable
  sudo: true

- name: Install Yubikey Desktop
  apt: name={{item}}
  with_items:
    - yubikey-neo-manager
    - yubioath-desktop
    - yubikey-personalization
    - yubikey-personalization-gui


